server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres
    username: postgres.flqdiseebhqbpfnmnoqv
    password: Thanhxuantrung123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: never

application:
  security:
    jwt:
      secret-key: YOUR_JWT_SECRET_KEY_AT_LEAST_256_BITS_LONG_CHANGE_ME_IN_PRODUCTION
      expiration: 86400000       # 1 day
      refresh-expiration: 604800000  # 7 days

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

